CC=g++
CFLAGS=--std=c++11
TARGETS = slide8 slide9 slide12 slide13 slide14 slide22 slide27 slide29

all: $(TARGETS)

slide8: slide8.cc
	$(CC) $(CFLAGS) -o $@ $<

slide9: slide9.cc
	$(CC) $(CFLAGS) -o $@ $<

slide12: slide12.cc
	$(CC) $(CFLAGS) -o $@ $<

slide13: slide13.cc
	$(CC) $(CFLAGS) -o $@ $<

slide14: slide14.cc
	$(CC) $(CFLAGS) -o $@ $<

slide22: slide22.cc
	$(CC) $(CFLAGS) -o $@ $<

slide27: slide27.cc
	$(CC) $(CFLAGS) -o $@ $<

slide29: slide29.cc
	$(CC) $(CFLAGS) -o $@ $<
